<?php

namespace ContainerVfgreoP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XvO9igcService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.xvO9igc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xvO9igc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'destinationRepo' => ['privates', 'App\\Repository\\DestinationRepository', 'getDestinationRepositoryService', true],
        ], [
            'destinationRepo' => 'App\\Repository\\DestinationRepository',
        ]);
    }
}
