<?php

namespace ContainerVfgreoP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDestinationService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.6cTfj6h.App\Entity\Destination' shared service.
     *
     * @return \App\Entity\Destination
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.6cTfj6h": it needs an instance of "App\\Entity\\Destination" but this type has been excluded in "config/services.yaml".');
    }
}
