<?php

namespace ContainerVfgreoP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDestinationTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\DestinationType' shared autowired service.
     *
     * @return \App\Form\DestinationType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\DestinationType'] = new \App\Form\DestinationType();
    }
}
