<?php

namespace ContainerVfgreoP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVoyageRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\VoyageRepository' shared autowired service.
     *
     * @return \App\Repository\VoyageRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\VoyageRepository'] = new \App\Repository\VoyageRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
