<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVfgreoP\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVfgreoP/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerVfgreoP.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerVfgreoP\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerVfgreoP\App_KernelProdContainer([
    'container.build_hash' => 'VfgreoP',
    'container.build_id' => 'e425caba',
    'container.build_time' => 1715781020,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVfgreoP');
