<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '56f0d7025711c308a8d85b32bb0588e1',
  'DATABASE_URL' => 'mysql://agencevoyage2:agencevoyage2@127.0.0.1:3306/agencevoyage2?serverVersion=11.2.2-MariaDB&charset=utf8mb4',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'MAILER_DSN' => 'native://default',
  'CORS_ALLOW_ORIGIN' => '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$',
);
